---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata: [ managedByLabel ]

namespace: grafana


resources:
  - ../../base/system


transformers:
  - ./transformers/annotations.yaml
  - ./transformers/label.yaml
  - ./transformers/prefixSuffix.yaml


# patches:
#   - target:
#       version: v1
#       kind: ConfigMap
#       name: (.*-k8s-?.*|.*-kube-state-metrics-?.*|.*-linux-ssh-logs-?.*|.*-node-exporter-full-?.*)
#     patch: |
#       - op: add
#         path: /metadata/annotations/grafana_dashboard_folder
#         value: "System"
