{
 "title": "Kubernetes / Events / View",
 "description": "Kubernetes Events Dashboard  by CloudXiaobai",
 "tags": [
  "loki",
  "kubernetes",
  "events"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Datasource", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Events Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({job=~\"$job\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Kubernetes Warning Enents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | type = \"Warning\" | __error__=\"\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Kubernetes Events Latest 24h",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} |= \"Error: ImagePullBackOff\" | json | reason = \"Failed\"  | line_format \"{{ .message }}\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "ImagePullBackOff"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"FailedScheduling\" | __error__ = \"\" [$__interval]))",
     "legendFormat": "FailedScheduling"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"SuccessfulDelete\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "SuccessfulDelete"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} |= \"failed liveness probe\" | json | reason = \"Killing\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "FailedLivenessProbe"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} |= \"Marking for deletion Pod\"| json | reason = \"ConntrackFull\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "ConntrackFull"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"Rebooted\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "NodeRebooted"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"OOMKilling\" | __error__ = \"\" [$__interval]))",
     "legendFormat": "ContainerOOM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"DockerHung\" | __error__ = \"\" [$__interval]))",
     "legendFormat": "DockerHung"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"BackOff\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "ContainerCrash"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"FailedMount\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "FailedMount"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | reason = \"SystemOOM\"| __error__ = \"\" [$__interval]))",
     "legendFormat": "NodeOOM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} |= \"Marking for deletion Pod\"| json | reason = \"TaintManagerEviction\" | __error__ = \"\" [$__interval]))",
     "legendFormat": "PodEvicted"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOP 10  Kubernetes Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10,sum by (reason) (count_over_time({job=~\"$job\"} | json | __error__ = \"\" [$__interval])))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Kubernetes Events Source",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | __error__ = \"\" [$__interval])) by (source_component)",
     "legendFormat": "{{source_component}}"
    }
   ]
  },
  {
   "title": "Kubernetes Event Type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"} | json | __error__ = \"\" [$__interval])) by (involvedObject_kind)",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  {
   "title": "Kubernetes Eviction Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (firstTimestamp,message) (count_over_time({job=~\"$job\"} |= \"Marking for deletion Pod\" | json | reason = \"TaintManagerEviction\" | __error__ = \"\"[$__interval]))",
     "legendFormat": "{{firstTimestamp}}    event occurred {{message}}"
    }
   ]
  }
 ]
}