---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./generators/rabbitmq-erlang-distribution.yaml
  - ./generators/rabbitmq-erlang-distributions-compare.yaml
  - ./generators/rabbitmq-erlang-memory-allocators.yaml
  - ./generators/rabbitmq-perf-test.yaml
  - ./generators/rabbitmq-quorum-queues-raft.yaml
  - ./generators/rabbitmq-stream.yaml
  - ./generators/rabbitmq.yaml
