---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata: [ managedByLabel ]

namespace: grafana


resources:
  - ../../base/general-spring_boot


transformers:
  - ./transformers/label.yaml
  - ./transformers/prefixSuffix.yaml
