---

apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: -loki-stack-monitoring

options:
  labels: {}
  annotations: {}

  disableNameSuffixHash: true

files:
  - loki-stack-monitoring.json=./files/loki-stack-monitoring.json
