---

apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: -nginx-service-mesh

options:
  labels: {}
  annotations: {}

  disableNameSuffixHash: true

files:
  - nginx-service-mesh.json=./files/nginx-service-mesh.json
