---

apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: -sealed-secrets

options:
  labels: {}
  annotations: {}

  disableNameSuffixHash: true

files:
  - sealed-secrets.json=./files/sealed-secrets.json
