---

apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: -jmx-exporter-httpserver

options:
  labels: {}
  annotations: {}

  disableNameSuffixHash: true

files:
  - jmx-exporter-httpserver.json=./files/jmx-exporter-httpserver.json
