---

apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: -rabbitmq-stream

options:
  labels: {}
  annotations: {}

  disableNameSuffixHash: true

files:
  - rabbitmq-stream.json=./files/rabbitmq-stream.json
