---

apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: -k8s-system-coredns

options:
  labels: {}
  annotations: {}

  disableNameSuffixHash: true

files:
  - k8s-system-coredns.json=./files/k8s-system-coredns.json
